### ISSUE TITLE
256 bytes question

### ISSUE THREAD

**Issue by HemanthJabalpuri** [Aefyr/PseudoApkSigner#1]
@Aefyr 
I think 256 bytes is not a constant number.
It depends on on the keysize according to https://github.com/fpg100/tiny-sign/blob/master/gen.sh.
That is testkey size is 2048 bytes, so we have to truncate last 256 bytes from it.
`cat CERT.RSA | openssl pkcs7 -inform DER -print_certs -text` will show the size of key.

README have to be changed according to this.

**Comment by Aefyr** [comment]
You're right, thanks for noticing. Fixed in https://github.com/Aefyr/PseudoApkSigner/commit/7d97b2abeda3595dc1b568158469d082b19ae695
